apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: prometheus:9090 
    isDefault: true
    access: proxy
    editable: true
    
  - name: Loki
    type: loki
    access: proxy
    url: loki:3100
    jsonData:
      maxLines: 1000

