{
 "title": "Logging",
 "description": "Universal and flexible dashboard for logging",
 "time": { "from": "now-1y", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Service",
    "query": "label_values({job=~\".+\"}, job)"
   },
   { "name": "levelname", "label": "Level", "query": "INFO, WARNING, ERROR" },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"$job\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: $levelname",
   "type": "stat",
   "description": "Total Count of $levelname in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"$job\", levelname=\"$levelname\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{job=\"$job\", levelname=\"$levelname\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total count of INFO / WARN / ERROR pie",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"$job\"})[$__interval])) by (levelname)",
     "legendFormat": "{{levelname}}"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" donut",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"$job\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (levelname)",
     "legendFormat": "{{levelname}}"
    }
   ]
  },
  {
   "title": "\"$levelname\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"$job\", levelname=\"$levelname\"})[$__interval])) * 100 / sum(count_over_time(({job=\"$job\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" historical",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"$job\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (levelname)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Rate per Levelname",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(({job=\"$job\", levelname=~\"$levelname\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (levelname)",
     "legendFormat": "{{levelname}}"
    }
   ]
  },
  {
   "title": "Count of logs historical",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"$job\"})[$__interval])) by (levelname)",
     "legendFormat": "{{levelname}}"
    }
   ]
  }
 ]
}