{
 "title": "Pipeline metrics",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "target",
    "query": "days, leadtime, prodtime, proddelay, prodwaste"
   }
  ]
 },
 "panels": [
  { "title": "Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Execution Time",
   "type": "table",
   "gridPos": { "h": 16, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.pre_process_docs\"}",
     "legendFormat": "Pre Process Docs"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.filter_docs\"}",
     "legendFormat": "Filter Docs"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.split_docs\"}",
     "legendFormat": "Split Docs"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.pre_processing\"}",
     "legendFormat": "Production Delays Pre Processing"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.filter\"}",
     "legendFormat": "Production Delays Filter"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.select\"}",
     "legendFormat": "Production Time Select"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.pedidos_usados_merge\"}",
     "legendFormat": "Pedidos Usados Merge"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.waste_ratio\"}",
     "legendFormat": "Waste Ratio"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.train_val_test_split\"}",
     "legendFormat": "Train/Val/Test split"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.encode\"}",
     "legendFormat": "Encoding"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.standardize\"}",
     "legendFormat": "Standardization"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.model_train_val\"}",
     "legendFormat": "Model training"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.model_test\"}",
     "legendFormat": "Model testing"
    }
   ]
  },
  {
   "title": "Node Execution Time",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.pre_process_docs\"}",
     "legendFormat": "Pre Process Docs"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.filter_docs\"}",
     "legendFormat": "Filter Docs"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.split_docs\"}",
     "legendFormat": "Split Docs"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.pre_processing\"}",
     "legendFormat": "Production Delays Pre Processing"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.filter\"}",
     "legendFormat": "Production Delays Filter"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.select\"}",
     "legendFormat": "Production Time Select"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.pedidos_usados_merge\"}",
     "legendFormat": "Pedidos Usados Merge"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.waste_ratio\"}",
     "legendFormat": "Waste Ratio"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.train_val_test_split\"}",
     "legendFormat": "Train/Val/Test split"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.encode\"}",
     "legendFormat": "Encoding"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.standardize\"}",
     "legendFormat": "Standardization"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.model_train_val\"}",
     "legendFormat": "Model training"
    },
    {
     "expr": "node_exec_time_seconds{job=\"kedro\", target=\"$target\", node_name=\"$target.model_test\"}",
     "legendFormat": "Model testing"
    }
   ]
  },
  {
   "title": "Total N.E.T. by Target",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(last_over_time(node_exec_time_seconds{job=\"kedro\"}[30d])) by (target)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Dataset Memory Usage ($target)",
   "type": "barchart",
   "description": "Memory used by each dataset troughout the pipeline.",
   "gridPos": { "h": 17, "w": 18, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "dataset_size_bytes{job=\"kedro\", target=\"$target\"}"
    }
   ]
  },
  {
   "title": "Total Memory Used ($target)",
   "type": "stat",
   "description": "Total memory used by all datasets related to target $target",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(last_over_time(dataset_size_bytes{job=\"kedro\", target=\"$target\"}[30d]))"
    }
   ]
  },
  {
   "title": "Total Memory Used by Target",
   "type": "barchart",
   "description": "Total memory used by all datasets related to each target.",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(last_over_time(dataset_size_bytes{job=\"kedro\"}[30d])) by (target)"
    }
   ]
  },
  { "title": "Model Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Mean Absolute Error (MAE)",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "select\n metrics.value as mae, tags.value as target\nfrom\n  metrics\njoin\n  runs\non\n  metrics.run_uuid=runs.run_uuid\njoin\n  tags\non\n  metrics.run_uuid=tags.run_uuid\nwhere\n  runs.status='FINISHED' and\n  tags.key='pipeline_name' and\n  metrics.key='MAE'"
    }
   ]
  },
  {
   "title": "MAE over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  metrics.value AS metric,\n  tags.value as target\nFROM metrics, tags\nWHERE\n  metrics.run_uuid=tags.run_uuid and\n  tags.key='pipeline_name' and\n  metrics.key='MAE'"
    }
   ]
  },
  {
   "title": "Movel versions",
   "type": "table",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "select\n  mv.name, mv.version, mv.current_stage, metrics.value as mae\nfrom\n  model_versions as mv, metrics\nwhere\n  mv.run_id = metrics.run_uuid and\n  metrics.key='MAE'\norder by\n  mv.name, mv.version"
    }
   ]
  },
  {
   "title": "Dataset shape",
   "type": "stat",
   "description": "Shape of the dataset used to train the model",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  params.key, params.value\nfrom\n  params, model_versions as mv, tags\nwhere\n  params.key like 'dataset.%' and\n  params.run_uuid = mv.run_id and\n  params.run_uuid = tags.run_uuid and\n  mv.current_stage = 'Production' and\n  tags.key = 'pipeline_name' and\n  tags.value = '${target}'"
    }
   ]
  },
  {
   "title": "Parameters",
   "type": "table",
   "description": "Parameters used by the pipeline to generate the $target model currently in production.",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT\n  params.key as parameter, params.value\nfrom\n  params, tags, model_versions as mv\nwhere\n  params.run_uuid=tags.run_uuid and\n  params.run_uuid=mv.run_id and\n  tags.key='pipeline_name' and\n  mv.current_stage='Production' and\n  tags.value='$target'\norder by parameter"
    }
   ]
  },
  {
   "title": "Target column",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 54 },
   "targets": [
    {
     "rawSql": "select\n  params.key, params.value\nfrom\n  params, model_versions as mv, tags\nwhere\n  params.key like 'target_column.%' and\n  params.run_uuid = mv.run_id and\n  params.run_uuid = tags.run_uuid and\n  mv.current_stage = 'Production' and\n  tags.key = 'pipeline_name' and\n  tags.value = '${target}'"
    }
   ]
  }
 ]
}