global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "monitor"

scrape_configs:
  - job_name: "kedro"
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]

remote_write:
  - url: "http://promscale:9201/write"
    remote_timeout: 30s
    queue_config:
      capacity: 10000
      max_samples_per_send: 3000
      batch_send_deadline: 10s
      min_shards: 4
      max_shards: 200
      min_backoff: 100ms
      max_backoff: 10s

remote_read:
  - url: "http://promscale:9201/read"
    read_recent: true
